version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
